title: "OCI Template example"
description: "OCI Template"
stackDescription: "OCI Template"
schemaVersion: 1.1.0
version: "20201125"
locale: "en"

variableGroups:
- title: "General Configuration"
  visible: false
  variables:
  - tenancy_ocid
  - user_ocid
  - fingerprint
  - private_key_path
  - region
  

- title: "Required Configuration"
  visible: true  
  variables:
  - compartment_id
  - customer_label
  - show_advanced 

- title: "Networking  Configuration"
  visible: 
      and:
        - show_advanced
  variables:
  - local.ips["vcn"]
  - local.ips["sub"]
  - local.ips.v1_domains["ip_v1_cl_domain"]
  
  

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  # General Configuration
  tenancy_ocid:
    title: "Tenancy ID"
    description: "The Oracle Cloud Identifier (OCID) for your tenancy"
    type: string
    required: true
    visibile: false

  region:
    title: "Region"
    description: "Choose Region where you deploy your application"
    type: oci:identity:region:name
    required: true
    visibile: true
  
  customer_label:
    title: "customer label"
    description: "Label used as a prefix for naming resources"
    type: string
    required: true
    visibile: false
  
  # Required Configuration
  compartment_id:
    title: "Compartment OCID"
    description: "Choose Comparment where you deploy your application"
    type: oci:identity:compartment:id
    required: true
    visibile: true

  
 # Network Configuration

  local.ips["vcn"]:
    type: string
    required: false
    default: "10.0.0.0/16"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR"
    description: "Choose single, contiguous IPv4 CIDR block for the VCN"
  
  local.ips["sub"]:
    type: string
    required: false
    default: "10.0.1.0/24"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Subnet IP - Prod External"
    description: "Choose single, contiguous IPv4 CIDR block for the Subnet"

  local.ips.v1_domains["ip_v1_cl_domain"]:
    type: string
    required: false
    default: "172.19.146.112/29"
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Subnet IP - Prod External"
    description: "Choose single, contiguous IPv4 CIDR block for the Subnet"


  